### ISSUE TITLE
nitroshare is just a garbage. it can not work for ubuntu18 between Android at all.

### ISSUE THREAD

**Issue by caixxiong** [nitroshare/nitroshare-desktop#243] opened 2020-01-13 02:37 UTC

**Comment by hhirsch** [comment] 2020-01-26 08:13
@caixxiong This looks like a duplicate of https://github.com/nitroshare/nitroshare-desktop/issues/222 

Can you confirm and close this issue?

**Comment by hhirsch** [comment] 2020-02-07 05:13
@nathan-osman This issue can be closed. It is a duplicate.

**Closed** 2020-02-07 06:28 UTC
