### ISSUE TITLE
Unable to listen on port 40818 (first use).

### ISSUE THREAD

**Issue by ntassani** [nitroshare/nitroshare-desktop#38] opened 2015-04-16 13:35 UTC
Hi, i recently install the new version of nitroshare.
The installation is ok, but opening the program i only get a window saying: Unable to listen on port 40818, and then the programm is closed.

The error is under ubuntu 14.04.
Any help?
Thanks!

**Comment by nathan-osman** [comment] 2015-04-16 17:54
I'm going to guess that this is caused by one of two things:

1. The port is in use by another application

    There should be an icon in the Unity panel (upper-right corner). Once you click on the icon, a menu will appear and you should be able to select "Settings". From there, you can change the port that NitroShare uses to listen for incoming transfer requests. (It's under the "Transfer Settings" section of the "Advanced" tab.)

    ![](http://i.stack.imgur.com/jGMEe.png)

2. NitroShare is already running

    You can verify that NitroShare is already running by opening a terminal and running the following command:

        pgrep nitroshare

    If you see one or more numbers displayed, this means the application is already running. For example, if I start NitroShare and then run the command, I see:

        nathan@nathan-desktop:~$ pgrep nitroshare
        4496

    If NitroShare isn't appearing in the menu, then it would probably be better to open a new issue to troubleshoot that.

**Comment by DexTheDewd** [comment] 2015-08-05 18:38
5 August 2015

Greetings:  I have just encountered the identical error -- but with Windows 8.1. Any chance you can direct me to the appropriate area within the system (netsh?) to open up this port (I'm guessing this is a firewall issue, as opposed to 'prior occupancy' of the port by another program), If this fact pattern does not necessarily imply a firewall issue, I would greatly appreciate any guidance on how to rectify the error so that I can use the program

**Comment by nathan-osman** [comment] 2015-08-05 18:58
That's a bit strange, since the installer automatically adds an exception to the Windows Firewall when it is installed. To confirm that the exception exists and is active, perform the following steps:

1. Press <kbd>Win</kbd> or click the Start Button and type "firewall"

2. Click the "Windows Firewall" entry

    ![Windows Firewall](http://i.stack.imgur.com/uYtrb.png)

3. Click the "Advanced settings" link on the left-hand side of the window that appears

    ![Advanced settings](http://i.stack.imgur.com/o7D9m.png)

4. Click the "Inbound Rules" link on the left-hand side of the window that appears and make sure both "NitroShare" entries have a green checkbox beside them

    ![Firewall Rules](http://i.stack.imgur.com/1wWLD.png)

Under nearly all circumstances, the only thing that could cause the "Unable to listen on port 40818" error message is another application (either NitroShare itself or something else) being already bound to the port. You can find out if the port is in use by opening up a command prompt and running the following command:

    netstat -an

**Comment by kantoquad** [comment] 2015-10-16 05:10
using ubuntu Gnome, can not get around the already taken port, any terminal commands

**Comment by nathan-osman** [comment] 2015-10-16 05:15
If NitroShare is already running, then the second instance will always fail to bind to the same port. Only a single instance is designed to be running at any given time.

**Comment by kantoquad** [comment] 2015-10-16 05:17
Thanks, but I am unsure how to change that

**Comment by nathan-osman** [comment] 2015-10-16 05:18
Do you mean change the port NitroShare binds to?

**Comment by kantoquad** [comment] 2015-10-16 05:25
yes, I used this in the past and really enjoyed it

**Comment by FabrizioMarana** [comment] 2016-07-09 12:53
@kantoquad : if you're unsure how to change the port NitroShare binds to, read this(https://github.com/nitroshare/nitroshare-desktop/issues/38#issuecomment-93801772)  few lines above.

**Comment by yueludanfeng** [comment] 2016-12-15 06:20
I have encountered the same problem and the reason is that NitroShare is already running ,
from the taskbar you can see an icon of NitroShare

**Comment by umasse** [comment] 2017-01-31 09:59
Maybe Nitroshare could check if another Nitroshare process is running, at least under the same user, and warn?

**Comment by peterkahl** [comment] 2017-06-03 08:00
This is a bit annoying.
Since my Ubuntu 16.04 XFCE doesn't show the Nitro icon, I tend to go to the launcher and start Nitroshare. Then I see the annoying `Unable to listen on port 40818` popup. It's because Nitro is already running and already listening on that port.

**Comment by nathan-osman** [comment] 2017-06-03 08:17
The upcoming release (0.3.4) will focus almost exclusively on mDNS support. After that, I'll be merging nearly 100 commits that I have in a separate branch. One of the things that will be fixed is this issue. QHttpEngine exposes a local API that NitroShare can use to check for currently running instances.

**Comment by peterkahl** [comment] 2017-06-03 08:19
@nathan-osman Good news. Thanks.

**Comment by nathan-osman** [comment] 2018-01-17 20:51
This should be fixed as of 9102d40. The application now displays a message if it is launched a second time while already running.

**Closed by nathan-osman** 2018-01-17 20:51 UTC

**Comment by jackpetrilli** [comment] 2019-06-15 18:06
This is most easily solved by creating a new Windows 10 firewall rule for both incoming and outcoming.  
Put Firewall in search box ->>> then Advanced Settings ----> next Inbound Rules ->>> then New Rule ->>> then Port (NOT PROGRAM) ->>>> then input 40818 --->>>> finish the wizard as it's self-explanatory.  I named the Rule "Nitroshare".  
Do the same for Outbound Rules.

Problem solved.

**Comment by abhishekdam27** [comment] 2020-08-06 03:55
> That's a bit strange, since the installer automatically adds an exception to the Windows Firewall when it is installed. To confirm that the exception exists and is active, perform the following steps:
> 
> 1. Press Win or click the Start Button and type "firewall"
> 2. Click the "Windows Firewall" entry
>    ![Windows Firewall](https://camo.githubusercontent.com/1281951f2a5c7729540011d77c84a9cdfb650ab7/687474703a2f2f692e737461636b2e696d6775722e636f6d2f75597472622e706e67)
> 3. Click the "Advanced settings" link on the left-hand side of the window that appears
>    ![Advanced settings](https://camo.githubusercontent.com/826cdc63a60b1d453154329ff9884f9f1cb2c600/687474703a2f2f692e737461636b2e696d6775722e636f6d2f6f3744396d2e706e67)
> 4. Click the "Inbound Rules" link on the left-hand side of the window that appears and make sure both "NitroShare" entries have a green checkbox beside them
>    ![Firewall Rules](https://camo.githubusercontent.com/d16cbba2db04525624f43a5277c6bc66e7d45d52/687474703a2f2f692e737461636b2e696d6775722e636f6d2f3177574c442e706e67)
> 
> Under nearly all circumstances, the only thing that could cause the "Unable to listen on port 40818" error message is another application (either NitroShare itself or something else) being already bound to the port. You can find out if the port is in use by opening up a command prompt and running the following command:
> 
> ```
> netstat -an
> ```

man,
![Screenshot (4)](https://user-images.githubusercontent.com/33367709/89488849-a8942900-d7c6-11ea-9556-0f53027737c8.png)
 I am having the same problem, so I ran that command in cmd and I found that that particular port's status is listening!

**Comment by kabelanbalachandran99** [comment] 2020-09-08 02:10
check for nitroshare on your hidden icons try( the up arrow near battery bar)

**Comment by kimcosmos** [comment] 2021-11-01 08:05
R Click the taskbar not the start menu! Basically you give no instructions for how to upload. So we are all opening the app expecting an interface and getting an error because its already running. New users must be told to RClick the taskbar icon. Even easier... stop multiple instances with a warning to check the taskbar for the interface. Not a misleading warning that the port is already taken. I found this through turning on my firewall and seeing it running and recieving files despite thinking its running. I only found the interface when I came to this issues page. So please... tweak your notification. Truly excellent app BTW. So fast and reliable.
