### ISSUE TITLE
No systray icon displayed in Mageia 6 with Plasma5

### ISSUE THREAD

**Issue by david-geiger** [nitroshare/nitroshare-desktop#77] opened 2016-07-11 07:07 UTC
Hi,

Latest Nitroshare 0.3.2 doesn't show any systray icon in Plasma5 (KDE5), unless it is called with:

$ env XDG_CURRENT_DESKTOP=plasma nitroshare

Regards,
David

**Comment by nathan-osman** [comment] 2016-07-11 07:24
Thanks for letting me know. Can you please provide the output of the following command?

    echo $XDG_CURRENT_DESKTOP

The fact that you need to set that environment variable suggests that its value is not the one NitroShare is expecting for KDE.

**Comment by david-geiger** [comment] 2016-07-11 07:44
output:

$ echo $XDG_CURRENT_DESKTOP
KDE
$

**Comment by nathan-osman** [comment] 2016-07-11 16:06
Excellent, thank you. I'll have this fixed in the next release.

**Comment by rapgro** [comment] 2016-07-11 17:06
Reproducible in Fedora 24, Plasma 5, Qt 5.6.1

**Comment by david-geiger** [comment] 2016-07-11 17:38
Hmmm! doesn't work here :(

**Comment by nathan-osman** [comment] 2016-07-11 17:49
@david-geiger what doesn't work?

**Comment by david-geiger** [comment] 2016-07-11 17:51
always no systray icon displayed after applying your patch.

and with it work only with:
$ env XDG_CURRENT_DESKTOP=plasma nitroshare

**Comment by nathan-osman** [comment] 2016-07-11 20:08
Hmm... that's odd. Let me install KDE on a VM and see if I can reproduce this behavior.

**Comment by nathan-osman** [comment] 2016-07-12 00:21
I tried to reproduce this with Plasma 5.5.5 on Ubuntu 16.04 but the icon appeared in the tray without the environment variable being set:

![konsole](https://cloud.githubusercontent.com/assets/1253444/16751002/dc022e52-478a-11e6-9423-e4820930d3e2.png)

**Comment by nathan-osman** [comment] 2016-07-12 03:22
Three hours later, I managed to get Mageia 6 installed :smile:

Indeed, the icon does not appear in the tray by default. However, it does show up under notifications, albeit without the icon:

![kde](https://cloud.githubusercontent.com/assets/1253444/16754175/f9274ae8-47a4-11e6-8507-64c925d0a993.png)

Switching it to an application indicator seems to work, so I'll implement that.

**Comment by nathan-osman** [comment] 2016-07-12 04:25
Hmm... further investigation yielded some interesting surprises. First of all, the application isn't using application indicators at all, as I had mistakenly thought. It appears that Qt is doing some magic here depending on the value of that environment variable. Setting `XDG_CURRENT_DESKTOP` to anything other than `KDE` seems to cause the icon to appear.

So it appears as though this is a feature of KDE and not a problem with NitroShare. If you right-click the tray and select the "Entries" panel, you can change the visibility of the NitroShare icon and have it appear in the tray.

![kde2](https://cloud.githubusercontent.com/assets/1253444/16755094/d3ae42b8-47ad-11e6-941f-6bb422c0690d.png)

However, there should be an icon appearing next to the entry in the menu. This is a problem with NitroShare and I will investigate further.

**Comment by david-geiger** [comment] 2016-07-12 04:57
Yes in my test I see that it shows up under notifications, only when the icon (tray.svg) is not displayed/found but if you start nitroshare with " env XDG_CURRENT_DESKTOP=plasma nitroshare" here you can see that the icon is displayed and that it appear now in the tray by default.

**Comment by nathan-osman** [comment] 2016-07-12 04:59
The `tray.svg` file is compiled into the binary, so it should never be missing.

**Comment by nathan-osman** [comment] 2016-07-12 06:24
It appears that the problem is because the icon is an SVG. I can get it to work with a PNG. This is very strange.

**Comment by nathan-osman** [comment] 2016-07-12 06:58
Seems to be fixed now. Please let me know if there are any problems.

**Closed** 2016-07-12 06:58 UTC

**Comment by david-geiger** [comment] 2016-07-12 17:49
Yes now it's good, the tray.svg icon is properly displayed.

Thanks a lot!
